# Home Assistant configuration for MkDocs automation integration
# Add this to your configuration.yaml or create a separate file

# RESTful service to trigger MkDocs rebuild
rest_command:
  mkdocs_rebuild:
    url: "http://localhost:8081/rebuild"
    method: POST
    headers:
      Content-Type: "application/json"
    payload: '{}'
    timeout: 30

# Sensor to check MkDocs API status
sensor:
  - platform: rest
    name: "MkDocs API Status"
    resource: "http://localhost:8081/status"
    method: GET
    json_attributes:
      - status
      - message
    value_template: "{{ value_json.status }}"
    scan_interval: 300  # Check every 5 minutes

# Example automation: Rebuild docs when files change

# Example script callable from UI
script:
  rebuild_mkdocs:
    alias: "Rebuild MkDocs Documentation"
    description: "Manually rebuild the MkDocs documentation"
    icon: mdi:book-refresh
    sequence:
      - service: rest_command.mkdocs_rebuild
      - service: notify.persistent_notification
        data:
          title: "MkDocs Rebuild"
          message: "Documentation rebuild started"
          notification_id: "mkdocs_rebuild"

# Input boolean to enable/disable auto rebuild
input_boolean:
  mkdocs_auto_rebuild:
    name: "MkDocs Auto Rebuild"
    icon: mdi:auto-fix
